### ISSUE TITLE
steps previous/next support

### ISSUE THREAD

**Issue by cadgerfeast** [cadgerfeast/steps-core#3]
Add the possibility to go to next/previous available step.

**Comment by Gosunet** [comment]
I was looking at this, any ideas to know the current step ?
I was thinking about saving the current step and updating it at every go.

**Comment by cadgerfeast** [comment]
You did already work on the select step issue.
I think a similar approach could work.
Finding the next step by incrementing the current step would be great.
As you said, we could save the current step at every go.

In the future, we could add a custom component to add to READMEs, that could validate a step.
Another custom component could do the `steps go` command for the user.
(But these features would be available only on `steps serve`.
